target_pattern: [[True, True, False], [True, False, True], [True, False, False], [False, True, True], [False, True, False], [False, False, True], [False, False, False]]
case_study_file: case_studies/mission1.yaml
MR_name: remove  # decrease or remove
num_of_obstacles: [1, 3]
index: [0, 2]  # index of the obstacle that will be decreased or removed
scale: [0.5, 0,9]  # degree of the reduction
repetitions: 3  # the number of repetitions for running each pair of test cases

# genetic algorithm
pop_size: 10
num_of_offsprings: 10
max_gen: 10



